# Ceci est le fichier de configuration en cas de changement de l'arborescence

# La lecture des chemins par l'application differe selon l'OS,
# veillez donc a toujours fournir le chemin absolu pour eviter les ambiguites et pour garantir le bon fonctionnement de l'application

# Exemples de chemins absolus :
# pour windows : C:\Projets\CAUE\DOSSIER CIBLE

# L'utilisation de / (pour linux) ou \ (pour windows) ne change rien, java traduit automatiquement en fonction de l'OS

watcher.dossierReception=CAUE/DOSSIER CIBLE
watcher.dossierRejet=CAUE/FICHIERS NON TRAITABLES
watcher.dossierConseils=CAUE/CONSEILS

# Intervalle en seconde entre chaque sondage du dossier cible
watcher.intervalleSondage=10

# Taille maximale pour UN seul fichier (ex: 20MB)
spring.servlet.multipart.max-file-size=20MB